### ISSUE TITLE
Use Jannovar for HGVS-variant to VCF conversion

### ISSUE THREAD

**Issue by xiamaz** [PEDIA-Charite/PEDIA-workflow#12]
Currently the HGVS-variant to VCF conversion does not work reliably, since parsing of HGVS-variants (originally pyhgvs) is decoupled from the variant annotation done in Jannovar.

It is possible to directly convert hgvs variants in Jannovar using a reference genome file. This would have several advantages:
* possibility for inclusion of multiple reference genomes
* easier tracking of errors arising later on in Jannovar annotation
* VCF-Generation and Annotations can be made entirely self-contained

**Necessary considerations:**
Jannovar can convert a list of hgvs variants into a single vcf file using jannovar-cli. For python interfacing it should be entirely possible to create bindings to integrate this process directly into the python code.

**Changes needed to the current codebase:**
Currently vcf creation is done in 1_qualityCheck and variant annotation done in 3_simulation. By using jannovar for both steps it should be entirely possible to achieve the same results by doing the vcf creation and annotations after phenomization and qualityCheck.

**Comment by la60312** [comment]
The goal is to convert HGVS to VCF format, and report the HGVS which can not be converted. If we want to use Jannovar to convert, we don't need to use the other library to check it first. We still have to check the HGVS code before convert it, because there are some HGVS codes with duplicate HGVS code or unrelated string. 

In the end, we need one VCF file for each case, and a report for cases which have problem with HGVS code. Then we fix the HGVS code manually, and run a script to apply the changes to those cases with problems.

**Comment by xiamaz** [comment]
> The goal is to convert HGVS to VCF format, and report the HGVS which can not be converted. If we want to use Jannovar to convert, we don't need to use the other library to check it first. We still have to check the HGVS code before convert it, because there are some HGVS codes with duplicate HGVS code or unrelated string.

Jannovar would actually take care of that, since duplicate HGVS entries would just get normalized away. The example in the jannovar documentation is exactly such a case, where multiple redundant hgvs strings have been entered.

We can generate one VCF using jannovar for each case and act on the reported errors. If we implemented that, external hgvs validation could be removed.

**Comment by visze** [comment]
If you find any bugs in jannovar please let us know. I will try to fix them
as soon as possible.

Or if you want to extend the manual. Feel free. It is all on GitHub

Right now you have to us the actual development version for hvbs to vcf
conversation because there was an ugly bug in fetching sequence from the
reference file. I will not make a release yet because this 'feature' is not
really used.

Cheers
Max

Am 01.03.2018 20:24 schrieb "Alcasa" <notifications@github.com>:

**Comment by GSalma** [comment]
I tested Jannovar with the list of all the HGVS in the 366 samples output in new_qc branch/ PEDIA-workflow/convert directory to see what kinds of errors we get.

Here is the list of extracted HGVS codes 

[new_qc_HGVS.txt](https://github.com/PEDIA-Charite/PEDIA-workflow/files/1774540/new_qc_HGVS.txt)

The output VCF file from Jannovar reported Parsing errors on some of them, but it stopped after processing only 22 codes with this exception : 

WARN Invalid reference nucleotides in 6:g.157517355C>T, should be T, auto-correcting.

 Exception in thread "main" java.lang.IllegalArgumentException: Duplicate allele added to 
       VariantContext: T

	at htsjdk.variant.variantcontext.VariantContext.makeAlleles(VariantContext.java:1487)
	at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:380)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:494)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:488)
	at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.writeVariant(ProjectTranscriptToChromosome.java:221)
	at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.processFile(ProjectTranscriptToChromosome.java:172)
	at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.run(ProjectTranscriptToChromosome.java:75)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:64)


**Output VCF file :** 
[new_qc_HGVS_vcf.txt](https://github.com/PEDIA-Charite/PEDIA-workflow/files/1774559/new_qc_HGVS_vcf.txt)

**Comment by GSalma** [comment]
I'm currently working on checking these errors..

**Comment by xiamaz** [comment]
@GSalma 
Are you giving all hgvs codes directly to the jannovar function? It seems to be an error with duplicate hgvs strings. Could you try just running the Jannovar VCF generation with eg
```
NM_017780.2:c.2520G>A  
  NM_017780.2:c.2520G>A
```
If so, my assumption that Jannovar works with duplicate HGVS strings would be false. In that case, would patching Jannovar for this usecase be reasonable? @visze

**Comment by visze** [comment]
**(Import) remark**: Don't upload the variants to the internet. Especially not to github and in particular not to an open guithub repository. One test variant etc. is fine but not all PEDIA variants.

The error is because the hgvs code is erroneous. If we lift the HGVS code over to genome coordinates we get this position: `6:g.157517355`. The reference has a `T` at this position. But HGVS sais: `C>T`. So jannovar correct the `C` to a `T`. Then we have `T>T`. Finally jannovar wants to write this variant into a VCF like `5 157517355 . T T` **BUT** in the VCF format is is NOT allowed to have the same ALT.  Therefore the super nice htsjdk library that generates the VCF fails.

The Jannovar HGVS-to-VCF assumes more or less correct HGVS codes. I think just checking if the HGVS code if it is correct will be a different functionality and is not implemented yet.

**Comment by visze** [comment]
@xiamaz I don't think it is because of the duplicated entries. I do not know what will happen if you add two identical copies of (correct) HGVS codes. Just try it out. But here I also have to pinpoint to the VCF format. It is not allowed to have two lines with the same position in the VCF file. So I think you should remove duplicated HGVS codes before.

**Comment by GSalma** [comment]
Re-duplicated entries. It runs, and produces to identical VCF entries, then continues through the list without breaking. 
 CHROM	POS            	ID   REF	 ALT	  QUAL	FILTER	INFO
1	        879317	         .	C	 T	 .	.	.
1	        879317	         .	C	 T	 .	.	.
6	      157527604	.	G	 T	 .	.	.

**Comment by xiamaz** [comment]
> It is not allowed to have two lines with the same position in the VCF file. So I think you should remove duplicated HGVS codes before.
@visze I think this would be the best case situation, but the issue would just be that this can quickly become non-trivial if we consider alternative builds/reference transcripts, different level (protein/genomic/transcript), that might or might not point to the same genomic mutation. Mutalyzer actually is able to handle identical transcripts, but it doesnt generate the VCF File format we would need. It would be possible to convert all hgvs codes to the genomic level using mutalyzer first and deduplicate them thereafter, but shouldn't it also be possible to leniently accept duplicated mutation information or would we get issues regarding zygosity and fringe cases where multiple duplicated hgvs strings are actually acceptable?

**Comment by GSalma** [comment]
@visze, I checked the correctness of one of the codes that produced the exception error, 
NM_020732.3:c.4110G>A
on both Mutalyzer and variantvalidator, and it seems correct. (reference used same as the one I used for jannovar, hg19)

**Comment by visze** [comment]
Which jannovar version do you use?

Am 02.03.2018 13:18 schrieb "GSalma" <notifications@github.com>:

**Comment by GSalma** [comment]
0.24

**Comment by visze** [comment]
Can you try the actual development version because of a nasty bug n
fetching the reference sequence?

Am 02.03.2018 14:24 schrieb "GSalma" <notifications@github.com>:

**Comment by GSalma** [comment]
Got the same error.

**Comment by visze** [comment]
Ok. Then please write a ticket in the jannovar repo

Am 02.03.2018 15:21 schrieb "GSalma" <notifications@github.com>:

**Comment by visze** [comment]
ok. same bug as before. please use the actual development version (v.25-snapshot).

You said that you tried the development version but it can't be the actual one...

**Comment by GSalma** [comment]
I used the 'develop' branch. I'm not sure where to get the v.25-snaphsot version.

**Comment by visze** [comment]
sorry it is v0.25-SNAPSHOT (not 25)
did you fetch the recent develop branch? like:

```bash
git checkout develop
git pull upstream develop
```

then you have to compile and pack jannovar:
```
mvn clean install package
```

then you should have the 0.25-SNAPSHOT version (also named like that) in the folder `jannovar-cli/target``

**Comment by GSalma** [comment]
Thanks! Found it and now I'm not getting that same error. I'll try running it with all our HGVS codes and keep you updated.

**Comment by GSalma** [comment]
@visze Most of the codes are converted now. A few give a parse error but the codes seem correct. 
example : NM_004260.3:c.3283delinsCC  :  Nucleotides must be given but were not in 3283delCCins
                 NM_017780.2:c.6322G>A  :  No transcript found for id NM_017780.2

**Comment by visze** [comment]
For `NM_004260.3:c.3283delinsCC` you maybe have to write `NM_004260.3:c.3283delGinsCC` can you check that?

About transcripts: That can happen that some of them are not found. When creating the database Jannovar directly downloads the latest refseq release for hg19 from NCBI. See here: https://github.com/charite/jannovar/blob/2b91917badc42b03506f49b58d86a688e61fd38e/jannovar-cli/src/main/resources/default_sources.ini#L128-L135

If the transcript is not present there it cannot be converted,

**Comment by GSalma** [comment]
Yes,  NM_004260.3:c.3283delGinsCC works like this.
