### ISSUE TITLE
gene specific allele frequency cutoffs

### ISSUE THREAD

**Issue by petkraw** [PEDIA-Charite/PEDIA-workflow#7]
Whiffin et al. presented a gene specific frequency threshold, that can be used for filtering exomes prior to the clinical interpretation. Their approach considers disease prevalence, heterogeneity and penetrance. They precomputed the cutoffs for all variants in Exac. This is already annotated in the ExAC vcfs:
ftp://ftp.broadinstitute.org/pub/ExAC_release/release1/freq_filter/README_for_af_filter_data.txt 
For further details, see: 
http://biorxiv.org/content/biorxiv/early/2016/09/02/073114.full.pdf
https://github.com/ImperialCardioGenetics/frequencyFilter
http://cardiodb.org/allelefrequencyapp/

**Comment by visze** [comment]
Okay this might be really simple. We are still using ExAC to annotate ALL vcfs. We are using right now v.0.3.1. (but release 1.0 is out now)

The important file is `ftp://ftp.broadinstitute.org/pub/ExAC_release/release1/freq_filter/af_filter_data.tsv.gz` We can generate a tabix index version out of it and then we can simply make lookups in the file for every variant. This is (of course) slow but if we prefilter with 1% it might be faster.

We can implement that in a SIMdrom filter in the exome-simulator

**Comment by visze** [comment]
I read the publication several times and I don't think we can use the precomputed data because it is just one side of the coin.

The precomputed data is the filtering allele frequency (derived by the upper limit of 95% confidence interval). But you need an own threshold to filter the variant (maximum credible population allele frequency). Therefor we need the disease prevalence and the penetrance. This will be different for every sample and (the goial of the study) we do not know the syndrom so we do not know these two values.

Figure 2 of the publication makes is clear I guess
